spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySql8Dialect
        format_sql: true
    show_sql: true
